### ISSUE TITLE
Compared to  pix2pix HD

### ISSUE THREAD

**Issue by cdq14** [johnryh/Face_Embedding_GAN#2]
It is a very good work!
I wonder whethe you have compared your work to pix2pixHD model  in FID score or other metric? Which one is better in this dateset？

**Comment by johnryh** [comment]
Thank you for your interest!  Please let me know if the following answers your question. 

**The short answer** 

We have not implemented the pix2pixHD model for our comparison experiments mainly due to its complexity to train. We may include that in our future work.

**The long answer**

The goal of our comparison experiments is to reveal the model capacity differences caused by the sample space mapping mechanism in almost identical conv-deconv structures, thus each implementation needs to be controlled in terms of model backbone complexity and hyperparameter tunning. For pix2pixHD it would actually be hard to achieve since it (1) requires additional networks blocks than our proposed structure in current implementation; (2) uses residual blocks that is theoretically more efficient in terms of model parameter counts. 

More importantly, pix2pixHD achieves varieties of generated output through "instance level embedding" --- meaning variations are coupled only with the perturbation of mask input, that intuitively may not make sense in many datasets

**Comment by cdq14** [comment]
Thank you for your answers! The long  answer did help. Wish you success!
